### ISSUE TITLE
use pmf with Ruby version?

### ISSUE THREAD

**Issue by nmehra222** [billgreenwald/Pubmed-Batch-Download#12]
Hi Bill,
Is it possible to use a pmf with the Ruby version of the script?
Thanks!

**Comment by billgreenwald** [comment]
It is not, and because of versioning and support, I migrated to python.  I would recommend it instead. 

If you know how to write Ruby, you can send me a push request and I'd gladly support it; if you have a restraint on using Ruby and not python, i am happy to try to help with getting python running in your environment

**Comment by nmehra222** [comment]
Okay, than you!
