### ISSUE TITLE
Trying to fetch pmid 30374447 ** fetching of reprint 30374447 failed from error ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by sayak1711** [billgreenwald/Pubmed-Batch-Download#9]

**Comment by billgreenwald** [comment]
This pdf does not exist on pubmed, which means this program cannot grab its PDF.  I don't know why you got the error BadStatusLine instead of 

** Reprint 30374447 cannot be fetched as pubmed does not have a link to its pdf.

As this is a non-fixable issue on the pubmed side, I am going to close this issue.  If you have any other documents you cannot grab, or want to try to troubleshoot why your error is different, please comment inside of your other thread instead of making different topics for each error.

Thanks!
